### ISSUE TITLE
Reviewed load fixture

### ISSUE THREAD

**Issue by meschac38700** [meschac38700/fastapi_getstarted#18]
It should be possible to load a model with a foreign key identified by its "natural name" which is a unique field.
```yaml
- model: hero.Hero
  properties:
    name: "Spider-Boy"
    secret_name: "Pedro Parqueador"
    user: "Pedro Parqueador" # natural name of the foreign key(user)

- model: hero.Hero
  properties:
    name: "Superman"
    secret_name: "Clark Kent"
    user: Clark Kent # natural name of the foreign key(user)
```
